# Site Settings
title: Joshua Young
email: joshua.y2506@gmail.com
description: >
  A test site
baseurl: ""
url: "http://joshua-y.github.io"
twitter_username:
github_username:  joshua-y
# Build Settings
sass:
  sass_dir: _sass
include: ['_pages']
kramdown:
  input: GFM
